// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMegtvSNP83s1PMR_0huAt9tge6DD7D-8',
    appId: '1:336505251470:web:9a797d8ce23c6b48c58bdf',
    messagingSenderId: '336505251470',
    projectId: 'fir-91fba',
    authDomain: 'fir-91fba.firebaseapp.com',
    storageBucket: 'fir-91fba.firebasestorage.app',
    measurementId: 'G-P4RHCHRC1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL4sh6jzxy5MLmITPTSXFiXLjqcUsujk4',
    appId: '1:336505251470:android:763f76667eea000cc58bdf',
    messagingSenderId: '336505251470',
    projectId: 'fir-91fba',
    storageBucket: 'fir-91fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-StoRl310K1NttsgQk24AZr75-Fe6PMU',
    appId: '1:336505251470:ios:9101bf4b0bdfc9e5c58bdf',
    messagingSenderId: '336505251470',
    projectId: 'fir-91fba',
    storageBucket: 'fir-91fba.firebasestorage.app',
    iosBundleId: 'com.example.googleTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-StoRl310K1NttsgQk24AZr75-Fe6PMU',
    appId: '1:336505251470:ios:9101bf4b0bdfc9e5c58bdf',
    messagingSenderId: '336505251470',
    projectId: 'fir-91fba',
    storageBucket: 'fir-91fba.firebasestorage.app',
    iosBundleId: 'com.example.googleTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMegtvSNP83s1PMR_0huAt9tge6DD7D-8',
    appId: '1:336505251470:web:25d4e6553bb0e2fac58bdf',
    messagingSenderId: '336505251470',
    projectId: 'fir-91fba',
    authDomain: 'fir-91fba.firebaseapp.com',
    storageBucket: 'fir-91fba.firebasestorage.app',
    measurementId: 'G-FHJTT3478C',
  );
}
